### PR TITLE
Adding network device accounting

### PR DESCRIPTION
**Pull request by c2defense**
Logging of activity on networking devices

### CODE REVIEW

**Comment by jcwilliamsATmitre** [comment]
Thanks @c2defense! We were discussing this and had some ideas to run by you:

1. I think we would just add the `Network` platform to existing data sources (ex: https://github.com/mitre-attack/attack-datasources/blob/main/Aggregating_Option/user_account.yml, https://github.com/mitre-attack/attack-datasources/blob/main/Aggregating_Option/file.yml) for some of the data components you proposed, which leads to #2

2. It seems like `Network Accounting` may have 2 data components that are unique, `command execution` (via something like the `cmd` + `cmd-arg` attributes since this really isn't a `Process` https://github.com/mitre-attack/attack-datasources/blob/main/Aggregating_Option/process.yml) and something to account for the config. I was looking through the links you shared and it seems like the latter may be captured in some form of system event, but what are your thoughts on the best way to capture `Network device configuration` + `Network device run-time memory` currently listed here (https://attack.mitre.org/techniques/T1601/)? Also, do you agree with this approach/see anymore `Network Accounting` specific components to consider?

Thanks again!

**Comment by c2defense** [comment]
These are good questions.  It kind of depends on the overall intent/structure goal.  Which was difficult for me to see, even after reading the blogs and the README, but I think more clear now with your comments.  Aggregation and extensible.

For number 1, I would say yes that makes complete sense.  I do see a potential issue with not every platform having all of the components of a data source.  Example: the file data source has file share creation, modification, deletion - those don't exist for Network platform.  Might there be a way to extend the schema to include a tag within each data source?

For number 2, I agree you cannot put the command execution in the process data source.  In fact, network devices do have process listings with network connections, so that kind of data would fit better there.  So I would add the Network platform to that data source, though not from "Accounting".  Netstat like process data is from the CLI output or from Network Device Syslog.  

For command and command arguments, its really the same as any shell, bash or windows, or network.  So I would say it could be called: Process command-line parameters like you have in https://attack.mitre.org/techniques/T1552/003/ OR have a separate data source for CLI/History.  Practioners don't necessarily collect "process data" to collect command line.  PowerShell Transcript logs, Bash_History files and Network Accounting are all similar in that aspect - collect what is the adversary typing into a shell.  I'm currently leaning towards "shell_command" being a separate data source.  Even "command prompt" isn't in process data.  

For network connection by process, it would fit well in the process data source, but network connection by user, does that go into user_account or process?  

For T1601, I don't think I would say that the actual configuration of a device becomes a data source?  I think that the intent is actually "File Monitoring".  If there is a modification to a running-config or a startup-config, there has been a file modified on disk or in memory.  So in fact you have the two correct data sources already, file and memory. I don't think its good to specify which file to monitor in that scenario.  As for "Memory Dump" its actually quite similar to Windows or Linux, so I would say "memory" becomes the common data source here, with all three platforms specified.  

So to keep with the theme of aggregation and extensibility, my suggestion is to add two additional data sources:
command.yml
memory.yml
And they can be used across all three platforms.  
And as you suggested, adding Network platform to user_account, file, and process.  Thoughts?

**Comment by jcwilliamsATmitre** [comment]
Thanks for the poke lol and sorry about the delay!

Exactly! The biggest priority is being able to map these to techniques (current and future) so we are specifically aiming for the model to be at the right level of abstraction to help convey what data we need to collect for a given technique without being overly brittle.

#1 - Really good point that we'll have to reconsider as we go forward, though the current thinking here is that we'd capture that via the mappings to techniques (i.e. Network infra specific techniques would only use appropriate components, though more may be listed for the data source)

#2 - Ahh ok that makes sense, I definitely want to run this by @Cyb3rPandaH but yeah I see your point in splitting commands and processes (especially for interactive terminals and associated log files).

If I'm tracking that example accurately, I think we would capture that via a relationship on process (since this is what links the user to the network connection - https://github.com/mitre-attack/attack-datasources/blob/main/Aggregating_Option/process.yml#L65).

Your proposal for file and memory for T1601 makes a lot of sense to me. I'm not sure where else we specify general memory (vice that of a specific process), but our next step is to start mapping these to specific techniques so we can explore then.

Thanks again for sharing your knowledge and perspective, this has been (and will continue to be) **SUPER** helpful!

**Comment by jcwilliamsATmitre** [comment]
Will have to circle back to also capture memory data source ideas

**Pull request merged**
